CREATE DATABASE jokesapi;
USE jokesapi;

CREATE TABLE jokes (
id SMALLINT UNSIGNED PRIMARY KEY,
type VARCHAR(50) DEFAULT "general",
setup TINYTEXT NOT NULL,
punchline TINYTEXT NOT NULL,
likes SMALLINT DEFAULT 0
);

-- DROP TABLE jokes;
-- SELECT * FROM jokes;
-- SELECT setup FROM jokes WHERE setup LIKE "%cat%" ORDER BY RAND() LIMIT 1;
-- SELECT MAX(id) FROM jokes;
-- SELECT DISTINCT type FROM jokes;
-- SELECT * FROM jokes ORDER BY likes DESC LIMIT 10;
-- SELECT * FROM jokes WHERE type = "knock-knock";
-- SELECT likes FROM jokes WHERE id = 400;
-- UPDATE jokes SET likes = 10 WHERE id = 400;

INSERT INTO jokes(id,type,setup,punchline) VALUES (1,'general','What did the fish say when it hit the wall?','Dam.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (2,'general','How do you make a tissue dance?','You put a little boogie on it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (3,'general','What''s Forrest Gump''s password?','1Forrest1');
INSERT INTO jokes(id,type,setup,punchline) VALUES (4,'general','What do you call a belt made out of watches?','A waist of time.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (5,'general','Why can''t bicycles stand on their own?','They are two tired');
INSERT INTO jokes(id,type,setup,punchline) VALUES (6,'general','How does a train eat?','It goes chew, chew');
INSERT INTO jokes(id,type,setup,punchline) VALUES (7,'general','What do you call a singing Laptop','A Dell');
INSERT INTO jokes(id,type,setup,punchline) VALUES (8,'general','How many lips does a flower have?','Tulips');
INSERT INTO jokes(id,type,setup,punchline) VALUES (9,'general','How do you organize an outer space party?','You planet');
INSERT INTO jokes(id,type,setup,punchline) VALUES (10,'general','What kind of shoes does a thief wear?','Sneakers');
INSERT INTO jokes(id,type,setup,punchline) VALUES (11,'general','What''s the best time to go to the dentist?','Tooth hurty.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (12,'knock-knock','Knock knock. Who''s there? A broken pencil. A broken pencil who?','Never mind. It''s pointless.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (13,'knock-knock','Knock knock. Who''s there? Cows go.  Cows go who?','No, cows go moo.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (14,'knock-knock','Knock knock.  Who''s there?  Little old lady.  Little old lady who?','I didn''t know you could yodel!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (15,'programming','What''s the best thing about a Boolean?','Even if you''re wrong, you''re only off by a bit.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (16,'programming','What''s the object-oriented way to become wealthy?','Inheritance');
INSERT INTO jokes(id,type,setup,punchline) VALUES (17,'programming','Where do programmers like to hangout?','The Foo Bar.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (18,'programming','Why did the programmer quit his job?','Because he didn''t get arrays.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (19,'general','Did you hear about the two silk worms in a race?','It ended in a tie.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (20,'general','What do you call a laughing motorcycle?','A Yamahahahaha.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (21,'general','A termite walks into a bar and says...','''Where is the bar tended?''');
INSERT INTO jokes(id,type,setup,punchline) VALUES (22,'general','What does C.S. Lewis keep at the back of his wardrobe?','Narnia business!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (23,'programming','Why do programmers always mix up Halloween and Christmas?','Because Oct 31 == Dec 25');
INSERT INTO jokes(id,type,setup,punchline) VALUES (24,'programming','A SQL query walks into a bar, walks up to two tables and asks...','''Can I join you?''');
INSERT INTO jokes(id,type,setup,punchline) VALUES (25,'programming','How many programmers does it take to change a lightbulb?','None that''s a hardware problem');
INSERT INTO jokes(id,type,setup,punchline) VALUES (26,'programming','If you put a million monkeys at a million keyboards, one of them will eventually write a Java program','the rest of them will write Perl');
INSERT INTO jokes(id,type,setup,punchline) VALUES (27,'programming','[''hip'', ''hip'']','(hip hip array)');
INSERT INTO jokes(id,type,setup,punchline) VALUES (28,'programming','To understand what recursion is...','You must first understand what recursion is');
INSERT INTO jokes(id,type,setup,punchline) VALUES (29,'programming','There are 10 types of people in this world...','Those who understand binary and those who don''t');
INSERT INTO jokes(id,type,setup,punchline) VALUES (30,'general','What did the duck say when he bought lipstick?','Put it on my bill');
INSERT INTO jokes(id,type,setup,punchline) VALUES (31,'general','What happens to a frog''s car when it breaks down?','It gets toad away');
INSERT INTO jokes(id,type,setup,punchline) VALUES (32,'general','did you know the first French fries weren''t cooked in France?','they were cooked in Greece');
INSERT INTO jokes(id,type,setup,punchline) VALUES (33,'programming','Which song would an exception sing?','Can''t catch me - Avicii');
INSERT INTO jokes(id,type,setup,punchline) VALUES (34,'knock-knock','Knock knock.  Who''s there?  Opportunity.','That is impossible. Opportunity doesn’t come knocking twice!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (35,'programming','Why do Java programmers wear glasses?','Because they don''t C#');
INSERT INTO jokes(id,type,setup,punchline) VALUES (36,'general','Why did the mushroom get invited to the party?','Because he was a fungi.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (37,'general','Do you know what the word ''was'' was initially?','Before was was was was was is.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (38,'general','I''m reading a book about anti-gravity...','It''s impossible to put down');
INSERT INTO jokes(id,type,setup,punchline) VALUES (39,'general','If you''re American when you go into the bathroom, and American when you come out, what are you when you''re in there?','European');
INSERT INTO jokes(id,type,setup,punchline) VALUES (40,'general','Want to hear a joke about a piece of paper?','Never mind...it''s tearable');
INSERT INTO jokes(id,type,setup,punchline) VALUES (41,'general','I just watched a documentary about beavers.','It was the best dam show I ever saw');
INSERT INTO jokes(id,type,setup,punchline) VALUES (42,'general','If you see a robbery at an Apple Store...','Does that make you an iWitness?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (43,'general','A ham sandwhich walks into a bar and orders a beer. The bartender says...','I''m sorry, we don''t serve food here');
INSERT INTO jokes(id,type,setup,punchline) VALUES (44,'general','Why did the Clydesdale give the pony a glass of water?','Because he was a little horse');
INSERT INTO jokes(id,type,setup,punchline) VALUES (45,'general','If you boil a clown...','Do you get a laughing stock?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (46,'general','Finally realized why my plant sits around doing nothing all day...','He loves his pot.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (47,'general','Don''t look at the eclipse through a colander.','You''ll strain your eyes.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (48,'general','I bought some shoes from a drug dealer.','I don''t know what he laced them with, but I was tripping all day!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (49,'general','Why do chicken coops only have two doors?','Because if they had four, they would be chicken sedans');
INSERT INTO jokes(id,type,setup,punchline) VALUES (50,'general','What do you call a factory that sells passable products?','A satisfactory');
INSERT INTO jokes(id,type,setup,punchline) VALUES (51,'general','When a dad drives past a graveyard: Did you know that''s a popular cemetery?','Yep, people are just dying to get in there');
INSERT INTO jokes(id,type,setup,punchline) VALUES (52,'general','Why did the invisible man turn down the job offer?','He couldn''t see himself doing it');
INSERT INTO jokes(id,type,setup,punchline) VALUES (53,'general','How do you make holy water?','You boil the hell out of it');
INSERT INTO jokes(id,type,setup,punchline) VALUES (54,'general','I had a dream that I was a muffler last night.','I woke up exhausted!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (55,'general','Why is peter pan always flying?','Because he neverlands');
INSERT INTO jokes(id,type,setup,punchline) VALUES (56,'programming','How do you check if a webpage is HTML5?','Try it out on Internet Explorer');
INSERT INTO jokes(id,type,setup,punchline) VALUES (57,'general','What do you call a cow with no legs?','Ground beef!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (58,'general','I dropped a pear in my car this morning.','You should drop another one, then you would have a pair.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (59,'general','Lady: How do I spread love in this cruel world?','Random Dude: [...💘]');
INSERT INTO jokes(id,type,setup,punchline) VALUES (60,'programming','A user interface is like a joke.','If you have to explain it then it is not that good.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (61,'knock-knock','Knock knock.  Who''s there?  Hatch.  Hatch who?','Bless you!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (62,'general','What do you call sad coffee?','Despresso.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (63,'general','Why did the butcher work extra hours at the shop?','To make ends meat.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (64,'general','Did you hear about the hungry clock?','It went back four seconds.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (65,'general','Well...','That’s a deep subject.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (66,'general','Did you hear the story about the cheese that saved the world?','It was legend dairy.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (67,'general','Did you watch the new comic book movie?','It was very graphic!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (68,'general','I started a new business making yachts in my attic this year...','The sails are going through the roof.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (69,'general','I got hit in the head by a soda can, but it didn''t hurt that much...','It was a soft drink.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (70,'general','I can''t tell if i like this blender...','It keeps giving me mixed results.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (71,'general','I couldn''t get a reservation at the library...','They were fully booked.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (72,'programming','I was gonna tell you a joke about UDP...','...but you might not get it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (73,'programming','The punchline often arrives before the set-up.','Do you know the problem with UDP jokes?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (74,'programming','Why do C# and Java developers keep breaking their keyboards?','Because they use a strongly typed language.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (75,'general','What do you give to a lemon in need?','Lemonaid.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (76,'general','Never take advice from electrons.','They are always negative.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (78,'general','Hey, dad, did you get a haircut?','No, I got them all cut.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (79,'general','What time is it?','I don''t know... it keeps changing.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (80,'general','A weasel walks into a bar. The bartender says, "Wow, I''ve never served a weasel before. What can I get for you?"','Pop,goes the weasel.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (81,'general','Bad at golf?','Join the club.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (82,'general','Can a kangaroo jump higher than the Empire State Building?','Of course. The Empire State Building can''t jump.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (83,'general','Can February march?','No, but April may.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (84,'general','Can I watch the TV?','Yes, but don’t turn it on.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (85,'general','Dad, can you put my shoes on?','I don''t think they''ll fit me.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (86,'general','Did you hear about the bread factory burning down?','They say the business is toast.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (87,'general','Did you hear about the chameleon who couldn''t change color?','They had a reptile dysfunction.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (88,'general','Did you hear about the cheese factory that exploded in France?','There was nothing left but de Brie.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (89,'general','Did you hear about the cow who jumped over the barbed wire fence?','It was udder destruction.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (90,'general','Did you hear about the guy who invented Lifesavers?','They say he made a mint.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (91,'general','Did you hear about the guy whose whole left side was cut off?','He''s all right now.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (92,'general','Did you hear about the kidnapping at school?','It''s ok, he woke up.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (93,'general','Did you hear about the Mexican train killer?','He had loco motives');
INSERT INTO jokes(id,type,setup,punchline) VALUES (94,'general','Did you hear about the new restaurant on the moon?','The food is great, but there’s just no atmosphere.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (95,'general','Did you hear about the runner who was criticized?','He just took it in stride');
INSERT INTO jokes(id,type,setup,punchline) VALUES (96,'general','Did you hear about the scientist who was lab partners with a pot of boiling water?','He had a very esteemed colleague.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (97,'general','Did you hear about the submarine industry?','It really took a dive...');
INSERT INTO jokes(id,type,setup,punchline) VALUES (98,'general','Did you hear that David lost his ID in prague?','Now we just have to call him Dav.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (99,'general','Did you hear that the police have a warrant out on a midget psychic ripping people off?','It reads "Small medium at large."');
INSERT INTO jokes(id,type,setup,punchline) VALUES (100,'general','Did you hear the joke about the wandering nun?','She was a roman catholic.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (101,'general','Did you hear the news?','FedEx and UPS are merging. They’re going to go by the name Fed-Up from now on.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (102,'general','Did you hear the one about the guy with the broken hearing aid?','Neither did he.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (103,'general','Did you know crocodiles could grow up to 15 feet?','But most just have 4.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (104,'general','What do ghosts call their true love?','Their ghoul-friend');
INSERT INTO jokes(id,type,setup,punchline) VALUES (105,'general','Did you know that protons have mass?','I didn''t even know they were catholic.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (106,'general','Did you know you should always take an extra pair of pants golfing?','Just in case you get a hole in one.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (107,'general','Do I enjoy making courthouse puns?','Guilty');
INSERT INTO jokes(id,type,setup,punchline) VALUES (108,'general','Do you know where you can get chicken broth in bulk?','The stock market.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (109,'general','Do you want a brief explanation of what an acorn is?','In a nutshell, it''s an oak tree.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (110,'general','Ever wondered why bees hum?','It''s because they don''t know the words.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (111,'general','Have you ever heard of a music group called Cellophane?','They mostly wrap.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (112,'general','Have you heard of the band 1023MB?','They haven''t got a gig yet.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (113,'general','Have you heard the rumor going around about butter?','Never mind, I shouldn''t spread it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (114,'general','How are false teeth like stars?','They come out at night!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (115,'general','How can you tell a vampire has a cold?','They start coffin.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (116,'general','How come a man driving a train got struck by lightning?','He was a good conductor.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (117,'general','How come the stadium got hot after the game?','Because all of the fans left.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (118,'general','How did Darth Vader know what Luke was getting for Christmas?','He felt his presents.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (119,'general','How did the hipster burn the roof of his mouth?','He ate the pizza before it was cool.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (120,'general','How do hens stay fit?','They always egg-cercise!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (121,'general','How do locomotives know where they''re going?','Lots of training');
INSERT INTO jokes(id,type,setup,punchline) VALUES (122,'general','How do the trees get on the internet?','They log on.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (123,'general','How do you find Will Smith in the snow?','Look for fresh prints.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (124,'general','How do you fix a broken pizza?','With tomato paste.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (125,'general','How do you fix a damaged jack-o-lantern?','You use a pumpkin patch.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (126,'general','How do you get a baby alien to sleep?','You rocket.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (127,'general','How do you get two whales in a car?','Start in England and drive West.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (128,'general','How do you know if there’s an elephant under your bed?','Your head hits the ceiling!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (129,'general','How do you make a hankie dance?','Put a little boogie in it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (130,'general','How good are you at Power Point?','I Excel at it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (131,'general','How do you organize a space party?','You planet.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (132,'general','How do you steal a coat?','You jacket.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (133,'general','How do you tell the difference between a crocodile and an alligator?','You will see one later and one in a while.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (134,'general','How does a dyslexic poet write?','Inverse.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (135,'general','How does a French skeleton say hello?','Bone-jour.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (136,'general','How does a penguin build it’s house?','Igloos it together.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (137,'general','How does a scientist freshen their breath?','With experi-mints!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (138,'general','How does the moon cut his hair?','Eclipse it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (139,'general','How many apples grow on a tree?','All of them!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (140,'general','How many bones are in the human hand?','A handful of them.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (141,'general','How many hipsters does it take to change a lightbulb?','Oh, it''s a really obscure number. You''ve probably never heard of it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (142,'general','How many kids with ADD does it take to change a lightbulb?','Let''s go ride bikes!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (143,'general','How many optometrists does it take to change a light bulb?','1 or 2? 1... or 2?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (144,'general','How many seconds are in a year?','12. January 2nd, February 2nd, March 2nd, April 2nd.... etc');
INSERT INTO jokes(id,type,setup,punchline) VALUES (145,'general','How many South Americans does it take to change a lightbulb?','A Brazilian');
INSERT INTO jokes(id,type,setup,punchline) VALUES (146,'general','How many tickles does it take to tickle an octopus?','Ten-tickles!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (147,'general','How much does a hipster weigh?','An instagram.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (148,'general','How was the snow globe feeling after the storm?','A little shaken.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (149,'general','Is the pool safe for diving?','It deep ends.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (150,'general','Is there a hole in your shoe?','No… Then how’d you get your foot in it?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (151,'general','What did the spaghetti say to the other spaghetti?','Pasta la vista, baby!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (152,'general','What’s 50 Cent’s name in Zimbabwe?','200 Dollars.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (153,'general','Want to hear a chimney joke?','Got stacks of em! First one''s on the house');
INSERT INTO jokes(id,type,setup,punchline) VALUES (154,'general','Want to hear a joke about construction?','Nah, I''m still working on it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (155,'general','Want to hear my pizza joke?','Never mind, it''s too cheesy.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (156,'general','What animal is always at a game of cricket?','A bat.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (157,'general','What are the strongest days of the week?','Saturday and Sunday...the rest are weekdays.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (158,'general','What biscuit does a short person like?','Shortbread.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (159,'general','What cheese can never be yours?','Nacho cheese.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (160,'general','What creature is smarter than a talking parrot?','A spelling bee.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (161,'general','What did celery say when he broke up with his girlfriend?','She wasn''t right for me, so I really don''t carrot all.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (162,'general','What did Michael Jackson name his denim store?','Billy Jeans!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (163,'general','What did one nut say as he chased another nut?','I''m a cashew!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (164,'general','What did one plate say to the other plate?','Dinner is on me!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (165,'general','What did one snowman say to the other snow man?','Do you smell carrot?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (166,'general','What did one wall say to the other wall?','I''ll meet you at the corner!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (167,'general','What did Romans use to cut pizza before the rolling cutter was invented?','Lil Caesars');
INSERT INTO jokes(id,type,setup,punchline) VALUES (168,'general','What did the 0 say to the 8?','Nice belt.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (169,'general','What did the beaver say to the tree?','It''s been nice gnawing you.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (170,'general','What did the big flower say to the littler flower?','Hi, bud!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (180,'general','What did the Buffalo say to his little boy when he dropped him off at school?','Bison.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (181,'general','What did the digital clock say to the grandfather clock?','Look, no hands!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (182,'general','What did the dog say to the two trees?','Bark bark.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (183,'general','What did the Dorito farmer say to the other Dorito farmer?','Cool Ranch!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (184,'general','What did the fish say when it swam into a wall?','Damn!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (185,'general','What did the grape do when he got stepped on?','He let out a little wine.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (186,'general','What did the judge say to the dentist?','Do you swear to pull the tooth, the whole tooth and nothing but the tooth?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (187,'general','What did the late tomato say to the early tomato?','I’ll ketch up');
INSERT INTO jokes(id,type,setup,punchline) VALUES (188,'general','What did the left eye say to the right eye?','Between us, something smells!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (189,'general','What did the mountain climber name his son?','Cliff.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (190,'general','What did the ocean say to the shore?','Nothing, it just waved.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (191,'general','Why don''t you find hippopotamuses hiding in trees?','They''re really good at it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (192,'general','What did the pirate say on his 80th birthday?','Aye Matey!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (193,'general','What did the Red light say to the Green light?','Don''t look at me I''m changing!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (194,'general','What did the scarf say to the hat?','You go on ahead, I am going to hang around a bit longer.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (195,'general','What did the shy pebble wish for?','That she was a little boulder.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (196,'general','What did the traffic light say to the car as it passed?','Don''t look I''m changing!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (197,'general','What did the Zen Buddist say to the hotdog vendor?','Make me one with everything.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (198,'general','What do birds give out on Halloween?','Tweets.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (199,'general','What do I look like?','A JOKE MACHINE!?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (200,'general','What do prisoners use to call each other?','Cell phones.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (201,'general','What do vegetarian zombies eat?','Grrrrrainnnnnssss.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (202,'general','What do you call a bear with no teeth?','A gummy bear!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (203,'general','What do you call a bee that lives in America?','A USB.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (204,'general','What do you call a boomerang that won''t come back?','A stick.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (205,'general','What do you call a careful wolf?','Aware wolf.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (206,'general','What do you call a cow on a trampoline?','A milk shake!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (207,'general','What do you call a cow with no legs?','Ground beef.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (208,'general','What do you call a cow with two legs?','Lean beef.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (209,'general','What do you call a crowd of chess players bragging about their wins in a hotel lobby?','Chess nuts boasting in an open foyer.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (210,'general','What do you call a dad that has fallen through the ice?','A Popsicle.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (211,'general','What do you call a dictionary on drugs?','High definition.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (212,'general','what do you call a dog that can do magic tricks?','a labracadabrador');
INSERT INTO jokes(id,type,setup,punchline) VALUES (213,'general','What do you call a droid that takes the long way around?','R2 detour.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (214,'general','What do you call a duck that gets all A''s?','A wise quacker.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (215,'general','What do you call a fake noodle?','An impasta.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (216,'general','What do you call a fashionable lawn statue with an excellent sense of rhythmn?','A metro-gnome');
INSERT INTO jokes(id,type,setup,punchline) VALUES (217,'general','What do you call a fat psychic?','A four-chin teller.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (218,'general','What do you call a fly without wings?','A walk.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (219,'general','What do you call a girl between two posts?','Annette.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (220,'general','What do you call a group of disorganized cats?','A cat-tastrophe.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (221,'general','What do you call a group of killer whales playing instruments?','An Orca-stra.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (222,'general','What do you call a monkey in a mine field?','A babooooom!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (223,'general','What do you call a nervous javelin thrower?','Shakespeare.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (224,'general','What do you call a pig that knows karate?','A pork chop!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (225,'general','What do you call a pig with three eyes?','Piiig');
INSERT INTO jokes(id,type,setup,punchline) VALUES (226,'general','What do you call a pile of cats?','A Meowtain.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (227,'general','What do you call a sheep with no legs?','A cloud.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (228,'general','What do you call a troublesome Canadian high schooler?','A poutine.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (229,'general','What do you call an alligator in a vest?','An in-vest-igator!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (230,'general','What do you call an Argentinian with a rubber toe?','Roberto');
INSERT INTO jokes(id,type,setup,punchline) VALUES (231,'general','What do you call an eagle who can play the piano?','Talonted!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (232,'general','What do you call an elephant that doesn’t matter?','An irrelephant.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (233,'general','What do you call an old snowman?','Water.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (234,'general','What do you call cheese by itself?','Provolone.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (235,'general','What do you call corn that joins the army?','Kernel.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (236,'general','What do you call someone with no nose?','Nobody knows.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (237,'general','What do you call two barracuda fish?','A Pairacuda!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (238,'general','What do you do on a remote island?','Try and find the TV island it belongs to.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (239,'general','What do you do when you see a space man?','Park your car, man.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (240,'general','What do you get hanging from Apple trees?','Sore arms.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (241,'general','What do you get when you cross a bee and a sheep?','A bah-humbug.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (242,'general','What do you get when you cross a chicken with a skunk?','A fowl smell!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (243,'general','What do you get when you cross a rabbit with a water hose?','Hare spray.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (244,'general','What do you get when you cross a snowman with a vampire?','Frostbite.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (245,'general','What do you give a sick lemon?','Lemonaid.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (246,'general','What does a clock do when it''s hungry?','It goes back four seconds!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (247,'general','What does a female snake use for support?','A co-Bra!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (248,'general','What does a pirate pay for his corn?','A buccaneer!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (249,'general','What does an angry pepper do?','It gets jalapeño face.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (250,'general','What happens to a frog''s car when it breaks down?','It gets toad.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (251,'general','What happens when you anger a brain surgeon?','They will give you a piece of your mind.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (252,'general','What has ears but cannot hear?','A field of corn.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (253,'general','What is a centipedes''s favorite Beatle song?','I want to hold your hand, hand, hand, hand...');
INSERT INTO jokes(id,type,setup,punchline) VALUES (254,'general','What is a tornado''s favorite game to play?','Twister!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (255,'general','What is a vampire''s favorite fruit?','A blood orange.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (256,'general','What is a witch''s favorite subject in school?','Spelling!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (257,'general','What is red and smells like blue paint?','Red paint!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (258,'general','What is the difference between ignorance and apathy?','I don''t know and I don''t care.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (259,'general','What is the hardest part about sky diving?','The ground.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (260,'general','What is the leading cause of dry skin?','Towels');
INSERT INTO jokes(id,type,setup,punchline) VALUES (261,'general','What is the least spoken language in the world?','Sign Language');
INSERT INTO jokes(id,type,setup,punchline) VALUES (262,'general','What is the tallest building in the world?','The library, it’s got the most stories!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (263,'general','What is this movie about?','It is about 2 hours long.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (264,'general','What kind of award did the dentist receive?','A little plaque.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (265,'general','What kind of bagel can fly?','A plain bagel.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (266,'general','What kind of dinosaur loves to sleep?','A stega-snore-us.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (267,'general','What kind of dog lives in a particle accelerator?','A Fermilabrador Retriever.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (268,'general','What kind of magic do cows believe in?','MOODOO.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (269,'general','What kind of music do planets listen to?','Nep-tunes.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (270,'general','What kind of pants do ghosts wear?','Boo jeans.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (271,'general','What kind of tree fits in your hand?','A palm tree!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (272,'general','What lies at the bottom of the ocean and twitches?','A nervous wreck.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (273,'general','What musical instrument is found in the bathroom?','A tuba toothpaste.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (274,'general','What time did the man go to the dentist?','Tooth hurt-y.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (275,'general','What type of music do balloons hate?','Pop music!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (276,'general','What was a more important invention than the first telephone?','The second one.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (277,'general','What was the pumpkin’s favorite sport?','Squash.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (278,'general','What''s black and white and read all over?','The newspaper.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (279,'general','What''s blue and not very heavy?','Light blue.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (280,'general','What''s brown and sticky?','A stick.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (281,'general','What''s orange and sounds like a parrot?','A Carrot.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (282,'general','What''s red and bad for your teeth?','A Brick.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (283,'general','What''s the best thing about elevator jokes?','They work on so many levels.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (284,'general','What''s the difference between a guitar and a fish?','You can tune a guitar but you can''t "tuna"fish!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (285,'general','What''s the difference between a hippo and a zippo?','One is really heavy, the other is a little lighter.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (286,'general','What''s the difference between a seal and a sea lion?','An ion!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (287,'general','What''s the worst part about being a cross-eyed teacher?','They can''t control their pupils.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (288,'general','What''s the worst thing about ancient history class?','The teachers tend to Babylon.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (289,'general','What’s brown and sounds like a bell?','Dung!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (290,'general','What’s E.T. short for?','He’s only got little legs.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (291,'general','What’s Forest Gump’s Facebook password?','1forest1');
INSERT INTO jokes(id,type,setup,punchline) VALUES (292,'general','What’s the advantage of living in Switzerland?','Well, the flag is a big plus.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (293,'general','What’s the difference between an African elephant and an Indian elephant?','About 5000 miles.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (294,'general','When do doctors get angry?','When they run out of patients.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (295,'general','When does a joke become a dad joke?','When it becomes apparent.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (296,'general','When is a door not a door?','When it''s ajar.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (297,'general','Where did you learn to make ice cream?','Sunday school.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (298,'general','Where do bees go to the bathroom?','The BP station.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (299,'general','Where do hamburgers go to dance?','The meat-ball.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (300,'general','Where do rabbits go after they get married?','On a bunny-moon.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (301,'general','Where do sheep go to get their hair cut?','The baa-baa shop.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (302,'general','Where do you learn to make banana splits?','At sundae school.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (303,'general','Where do young cows eat lunch?','In the calf-ateria.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (304,'general','Where does batman go to the bathroom?','The batroom.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (305,'general','Where does Fonzie like to go for lunch?','Chick-Fil-Eyyyyyyyy.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (306,'general','Where does Napoleon keep his armies?','In his sleevies.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (307,'general','Where was the Declaration of Independence signed?','At the bottom!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (308,'general','Where’s the bin?','I haven’t been anywhere!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (309,'general','Which side of the chicken has more feathers?','The outside.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (310,'general','Who did the wizard marry?','His ghoul-friend');
INSERT INTO jokes(id,type,setup,punchline) VALUES (311,'general','Who is the coolest Doctor in the hospital?','The hip Doctor!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (312,'general','Why are fish easy to weigh?','Because they have their own scales.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (313,'general','Why are fish so smart?','Because they live in schools!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (314,'general','Why are ghosts bad liars?','Because you can see right through them!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (315,'general','Why are graveyards so noisy?','Because of all the coffin.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (316,'general','Why are mummys scared of vacation?','They''re afraid to unwind.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (317,'general','Why are oranges the smartest fruit?','Because they are made to concentrate.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (318,'general','Why are pirates called pirates?','Because they arrr!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (319,'general','Why are skeletons so calm?','Because nothing gets under their skin.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (320,'general','Why can''t a bicycle stand on its own?','It''s two-tired.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (321,'general','Why can''t you use "Beef stew"as a password?','Because it''s not stroganoff.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (322,'general','Why can''t your nose be 12 inches long?','Because then it''d be a foot!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (323,'general','Why can’t you hear a pterodactyl go to the bathroom?','The p is silent.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (324,'general','Why couldn''t the kid see the pirate movie?','Because it was rated arrr!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (325,'general','Why couldn''t the lifeguard save the hippie?','He was too far out, man.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (326,'general','Why did Dracula lie in the wrong coffin?','He made a grave mistake.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (327,'general','Why did Sweden start painting barcodes on the sides of their battleships?','So they could Scandinavian.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (328,'general','Why did the A go to the bathroom and come out as an E?','Because he had a vowel movement.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (329,'general','Why did the barber win the race?','He took a short cut.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (330,'general','Why did the belt go to prison?','He held up a pair of pants!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (331,'general','Why did the burglar hang his mugshot on the wall?','To prove that he was framed!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (332,'general','Why did the chicken get a penalty?','For fowl play.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (333,'general','Why did the Clydesdale give the pony a glass of water?','Because he was a little horse!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (334,'general','Why did the coffee file a police report?','It got mugged.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (335,'general','Why did the cookie cry?','Because his mother was a wafer so long');
INSERT INTO jokes(id,type,setup,punchline) VALUES (336,'general','Why did the cookie cry?','It was feeling crumby.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (337,'general','Why did the cowboy have a weiner dog?','Somebody told him to get a long little doggy.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (338,'general','Why did the fireman wear red, white, and blue suspenders?','To hold his pants up.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (339,'general','Why did the girl smear peanut butter on the road?','To go with the traffic jam.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (340,'general','Why did the half blind man fall in the well?','Because he couldn''t see that well!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (341,'general','Why did the house go to the doctor?','It was having window panes.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (342,'general','Why did the kid cross the playground?','To get to the other slide.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (343,'general','Why did the man put his money in the freezer?','He wanted cold hard cash!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (344,'general','Why did the man run around his bed?','Because he was trying to catch up on his sleep!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (345,'general','Why did the melons plan a big wedding?','Because they cantaloupe!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (346,'general','Why did the octopus beat the shark in a fight?','Because it was well armed.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (347,'general','Why did the opera singer go sailing?','They wanted to hit the high Cs.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (348,'general','Why did the scarecrow win an award?','Because he was outstanding in his field.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (349,'general','Why did the tomato blush?','Because it saw the salad dressing.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (350,'general','Why did the tree go to the dentist?','It needed a root canal.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (351,'general','Why did the worker get fired from the orange juice factory?','Lack of concentration.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (352,'general','Why didn''t the number 4 get into the nightclub?','Because he is 2 square.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (353,'general','Why didn’t the orange win the race?','It ran out of juice.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (354,'general','Why didn’t the skeleton cross the road?','Because he had no guts.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (355,'general','Why do bananas have to put on sunscreen before they go to the beach?','Because they might peel!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (356,'general','Why do bears have hairy coats?','Fur protection.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (357,'general','Why do bees have sticky hair?','Because they use honey combs!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (358,'general','Why do bees hum?','Because they don''t know the words.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (359,'general','Why do birds fly south for the winter?','Because it''s too far to walk.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (360,'general','Why do choirs keep buckets handy?','So they can carry their tune');
INSERT INTO jokes(id,type,setup,punchline) VALUES (361,'general','Why do crabs never give to charity?','Because they’re shellfish.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (362,'general','Why do ducks make great detectives?','They always quack the case.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (363,'general','Why do mathematicians hate the U.S.?','Because it''s indivisible.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (364,'general','Why do pirates not know the alphabet?','They always get stuck at "C".');
INSERT INTO jokes(id,type,setup,punchline) VALUES (365,'general','Why do pumpkins sit on people’s porches?','They have no hands to knock on the door.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (366,'general','Why do scuba divers fall backwards into the water?','Because if they fell forwards they’d still be in the boat.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (367,'general','Why do trees seem suspicious on sunny days?','Dunno, they''re just a bit shady.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (368,'general','Why do valley girls hang out in odd numbered groups?','Because they can''t even.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (369,'general','Why do wizards clean their teeth three times a day?','To prevent bat breath!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (370,'general','Why do you never see elephants hiding in trees?','Because they''re so good at it.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (371,'general','Why does a chicken coop only have two doors?','Because if it had four doors it would be a chicken sedan.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (372,'general','Why does a Moon-rock taste better than an Earth-rock?','Because it''s a little meteor.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (373,'general','Why does it take longer to get from 1st to 2nd base, than it does to get from 2nd to 3rd base?','Because there’s a Shortstop in between!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (374,'general','Why does Norway have barcodes on their battleships?','So when they get back to port, they can Scandinavian.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (375,'general','Why does Superman get invited to dinners?','Because he is a Supperhero.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (376,'general','Why does Waldo only wear stripes?','Because he doesn''t want to be spotted.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (377,'programming','Knock-knock.','A race condition. Who is there?');
INSERT INTO jokes(id,type,setup,punchline) VALUES (378,'programming','What''s the best part about TCP jokes?','I get to keep telling them until you get them.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (379,'programming','A programmer puts two glasses on his bedside table before going to sleep.','A full one, in case he gets thirsty, and an empty one, in case he doesn’t.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (380,'programming','There are 10 kinds of people in this world.','Those who understand binary, those who don''t, and those who weren''t expecting a base 3 joke.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (381,'general','Two guys walk into a bar . . .','The first guy says "Ouch!" and the second says "Yeah, I didn''t see it either."');
INSERT INTO jokes(id,type,setup,punchline) VALUES (382,'programming','What did the router say to the doctor?','It hurts when IP.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (383,'programming','An IPv6 packet is walking out of the house.','He goes nowhere.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (384,'programming','A DHCP packet walks into a bar and asks for a beer.','Bartender says, "here, but I’ll need that back in an hour!"');
INSERT INTO jokes(id,type,setup,punchline) VALUES (385,'programming','3 SQL statements walk into a NoSQL bar. Soon, they walk out','They couldn''t find a table.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (386,'general','I saw a nice stereo on Craigslist for $1. Seller says the volume is stuck on ‘high’','I couldn’t turn it down.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (388,'programming','What’s the object-oriented way to become wealthy?','Inheritance.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (389,'general','What do you call a bee that can''t make up its mind?','A maybe.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (390,'general','Why was Cinderalla thrown out of the football team?','Because she ran away from the ball.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (391,'general','What kind of music do welders like?','Heavy metal.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (392,'general','Why are “Dad Jokes” so good?','Because the punchline is apparent.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (393,'programming','Java developers wear glasses.','Because they can''t C#.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (394,'programming','Why dot net developers don''t wear glasses?','Because they see sharp.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (395,'general','Why is seven bigger than nine?','Because seven ate nine.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (396,'dad','Why do fathers take an extra pair of socks when they go golfing?','In case they get a hole in one!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (397,'general','What do you call a suspicious looking laptop?','Asus');
INSERT INTO jokes(id,type,setup,punchline) VALUES (398,'programming','What did the Java code say to the C code?','You''ve got no class.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (399,'programming','What is the most used language in programming?','Profanity.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (400,'programming','Why do programmers always get Christmas and Halloween mixed up?','Because DEC 25 = OCT 31');
INSERT INTO jokes(id,type,setup,punchline) VALUES (401,'programming','What goes after USA?','USB.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (402,'dad','Why don''t eggs tell jokes?','Because they would crack each other up.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (403,'general','How do you make the number one disappear?','Add the letter G and it’s “gone”!');
INSERT INTO jokes(id,type,setup,punchline) VALUES (404,'general','My older brother always tore the last pages of my comic books, and never told me why.','I had to draw my own conclusions.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (405,'general','The Sergeant-Major growled at the young soldier: I didn’t see you at camouflage training this morning.','Thank you very much, sir.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (406,'general','Why does Waldo only wear stripes?','Because he doesn''t want to be spotted.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (407,'programming','A male developer often gets called as a Dev, then what would you call a female developer?.','Devi.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (408,'general','Why did the kid throw the watch out the window?','So time would fly.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (409,'programming','Where did the API go to eat?','To the RESTaurant.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (410,'food','Why did the rooster cross the road?','He heard that the chickens at KFC were pretty hot.');
INSERT INTO jokes(id,type,setup,punchline) VALUES (411,'general','What did the ocean say to the beach?','Thanks for all the sediment.');